--- 
- name: creating user and creating files/directries in users home dir
  hosts: all
  tasks:
   - name: create users
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: create files/directies
     file:
      name: "{{d}}"
      state: "{{e}}"
...      
