---
- name: create CI_CD setup of jenkins
  hosts: 172.31.42.34
  tasks:
   - name: install s/w necessary for jenkins
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - openjdk-8-jdk
      - git
      - maven
   - name: download jenkins.war
     get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: /tmp
- name: configure qa and prod servers
  hosts: webserver
  tasks:
   - name: install tomcat8 and tomcat8-admin
     apt:
      name: "{{item}}"
      state: present
     with_items:
      - tomcat8
      - tomcat8-admin
   - name: copy the tomcat-users file into qa and prod servers
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat8

