---
- name: install sw for CI
  hosts: servers
  tasks:
   - name: install sw's
     apt:
      name: "{{item}}"
      state: present
     with_items:
      - openjdk-8-jdk
      - git
      - maven
      - tomcat8
      - tomcat8-admin
- name: download the dev code and create an artifact
  hosts: devserver
  tasks:
   - name: continuous download
     git:
      repo: https://github.com/dhirendrakb/dhirenrepo.git
      dest: /home/ubuntu/project-code
   - name: continuous build
     shell: cd /home/ubuntu/project-code;mvn package



