---
- name: install/uninstall /upgrade sw applicataion
  hosts: all
  tasks: 
   - name: install or uninstall or upgrade sw
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: openjdk-8-jdk,b: absent,c: no}
      - {a: git,b: latest,c: no}
      - {a: firewalld,b: absent,c: yes}
...
