---
- name: implementing handler
  hosts: all
  tasks:
   - name: apache2
     apt:
      name: apache2
      state: present
     notify: check url response
   - name: edit index.html file
     copy:
      content: "welcome to intelliq\n"
      dest: /var/www/html/index.html
     notify: restart apache2
  handlers:
   - name: restart apache2
     service:
      name: apache2
      state: restarted
   - name: check url response
     uri:
      url: "{{item}}"
      status: 200
     with_items:
      - http://172.31.34.210
      - http://172.31.42.34
      - http://172.31.39.209
...
           


